event_finder/event/routes.py
from flask import (Blueprint, render_template, request,
                   redirect, session, flash, url_for, abort)
from event_finder import db
from datetime import datetime
from event_finder.event.models import Event, User, Profile, Attendance
from event_finder.helpers import db_find_first, validate_form_data
import random

event = Blueprint("event", __name__,
                  template_folder="../event_finder/templates")


@event.route("/")
def index():
    """
    Route returns the index page with two random events.

    :return:
        event_one - The first random event
        event_two - The second random event
        render_template("index.html")
    """
    current_events = list(Event.query.filter(
        Event.date >= datetime.utcnow()).all())
    if current_events:
        # Use random to generate a random number between 0
        # and the length of current_events -1
        event_one = current_events[random.randint(0, len(current_events) - 1)]
        event_two = current_events[random.randint(0, len(current_events) - 1)]
        return render_template("index.html",
                               event_one=event_one, event_two=event_two)
    return render_template("index.html")


@event.route("/events")
def events():
    """
    Route returns the events page with a list of all events.

    :return:
        event_list - A list of all events
        render_template("events/events.html")
    """
    page = request.args.get('page', 1, type=int)
    current_date = datetime.utcnow().date()
    event_list = Event.query.filter(Event.date >= current_date) \
        .order_by(Event.date).paginate(page=page, per_page=10)
    return render_template("events/events.html", events=event_list)


@event.route("/events/<int:event_id>")
def event_info(event_id):
    """
    Route returns the event info page for a specific event.

    :param event_id:
    :return:
        event_data - The event data for the event
        render_template("events/event_info.html")
    """
    event_data = db_find_first(Event, id=event_id)
    # If the event doesn't exist, return a 404 error
    if not event_data:
        abort(404)

    user = db_find_first(User, uuid=session.get("user_uuid"))
    # If the user is logged in, check if they are registered for the event
    if user:
        existing_registration = Attendance.query \
            .filter_by(user_id=user.id, event_id=event_id).first()
        return render_template("events/event_info.html",
                               event=event_data,
                               existing_registration=existing_registration)

    return render_template("events/event_info.html", event=event_data)


@event.route("/events/create_event", methods=["GET", "POST"])
def create_event():
    """
     Route returns the create event page.

    :return:
        render_template("events/create_event.html") on GET request
        render_template("events/create_event.html") on failed POST request
        redirect(url_for("event.events")) on POST request
    """
    user = db_find_first(User, uuid=session.get("user_uuid"))
    if not user:
        flash("You must be logged in to create an event.")
        abort(403)
        return redirect("error/403.html")

    if request.method == "POST":
        title = request.form.get("title")
        description = request.form.get("description")
        location = request.form.get("location")
        date = request.form.get("date")
        start_time = datetime.strptime(request.form.get("start_time"),
                                       "%H:%M").time()
        end_time = datetime.strptime(request.form.get("end_time"),
                                     "%H:%M").time()

        form_data = request.form
        is_valid, message = validate_form_data(form_data, "event")
        if not is_valid:
            flash(message)
            return redirect(url_for("event.create_event"))

        date = datetime.strptime(date, "%Y-%m-%d").date()

        # Check if the event date is in the past
        if date < datetime.utcnow().date():
            flash("Event date must be in the future.")
            return render_template("events/create_event.html")

        # Check if all fields are filled out
        event_fields = [title, description,
                        location, date, start_time, end_time]
        for field in event_fields:
            if not field:
                flash(f"Please fill out the required fields.")
                return render_template("events/create_event.html")
        new_event = Event(title=title, description=description,
                          location=location, date=date,
                          start_time=start_time, end_time=end_time,
                          creator_id=user.uuid)
        db.session.add(new_event)
        db.session.commit()
        flash("Event created successfully.")
        return redirect(url_for("event.events"))

    return render_template("events/create_event.html")


@event.route("/events/<int:event_id>/edit_event", methods=["GET", "POST"])
def edit_event(event_id):
    """
    Route returns the edit event page.

    Form fields are pre-populated with the event data.
    :param event_id:
    :return:
        event_to_edit - The event data for the event
        event_date - The event date in the format YYYY-MM-DD
        event_start_date - The event start time in the format HH:MM
        event_end_date - The event end time in the format HH:MM
        render_template("events/edit_event.html") on GET request
        redirect(url_for("event.events")) on POST request

    """
    event_to_edit = db_find_first(Event, id=event_id)
    event_date = event_to_edit.date.strftime("%Y-%m-%d")
    event_start_date = event_to_edit.start_time.strftime("%H:%M")
    event_end_date = event_to_edit.end_time.strftime("%H:%M")
    if request.method == "POST":
        event_to_edit.title = request.form.get("title")
        event_to_edit.description = request.form.get("description")
        event_to_edit.location = request.form.get("location")
        event_to_edit.date = request.form.get("date")
        event_to_edit.start_time = request.form.get("start_time")
        event_to_edit.end_time = request.form.get("end_time")

        form_data = request.form
        is_valid, message = validate_form_data(form_data, "event")
        if not is_valid:
            flash(message)
            return redirect(url_for("event.edit_event", event_id=event_id))

        db.session.add(event_to_edit)
        db.session.commit()
        return redirect(url_for("event.events"))

    return render_template("events/edit_event.html",
                           event=event_to_edit, event_date=event_date,
                           event_start_date=event_start_date,
                           event_end_date=event_end_date)


@event.route("/events/<int:event_id>/delete")
def delete_event(event_id):
    """
    Route deletes an event and all associated attendance records.

    :param event_id:
    :return:
        redirect(url_for("event.events"))
    """
    event_to_delete = db_find_first(Event, id=event_id)
    Attendance.query.filter_by(event_id=event_to_delete.id).delete()
    db.session.delete(event_to_delete)
    db.session.commit()
    return redirect(url_for("event.events"))


@event.route("/events/<int:event_id>/register")
def event_registration(event_id):
    """
    Route registers a user for an event.

    Redirects user to the event info page on click.
    :param event_id:
    :return:
        redirect(url_for("event.event_info", event_id=event_id))
    """
    user = db_find_first(User, uuid=session.get("user_uuid"))
    registration = Attendance.__table__.insert() \
        .values(user_id=user.id, event_id=event_id)
    db.session.execute(registration)
    db.session.commit()
    flash("You are now registered for this event.")
    return redirect(url_for("event.events"))


@event.route("/events/<int:event_id>/unregister")
def event_deregister(event_id):
    """
     Route deregisters a user from an event.

    Redirects user to the event info page on click.

    :param event_id:
    :return:
        redirect(url_for("event.event_info", event_id=event_id))
    """
    user = db_find_first(User, uuid=session.get("user_uuid"))
    db.session.execute(Attendance.__table__.delete().filter(
        Attendance.user_id == user.id, Attendance.event_id == event_id))
    db.session.commit()
    flash("You are now unregistered from this event.")
    return redirect(url_for("event.events"))


@event.route("/profile/<uuid>")
def profile(uuid):
    """
    Route returns the profile page.

    :param uuid:
    :return:
        user_profile - The profile data for the user
        events_created - The events created by the user
        events_attending - The events the user is attending
        render_template("profile.html")
    """
    user = db_find_first(User, uuid=uuid)

    if uuid == "not_set":
        flash("You must be logged in to view this page.")
        return redirect(url_for("auth.login"))

    if not user:
        abort(404)
        return redirect(url_for("auth.login"))

    if user.uuid != session.get("user_uuid"):
        flash("You do not have permission to view this profile.")
        abort(403)
        return redirect("error/403.html")

    user_profile = Profile.query.filter_by(user_uuid=user.uuid).first()

    events_created = Event.query.filter_by(creator_id=user.uuid) \
        .order_by(Event.date)

    events_attending = Event.query.join(Attendance) \
        .filter_by(user_id=user.id) \
        .order_by(Event.date)

    return render_template("profile.html", user=user, profile=user_profile,
                           created_events=events_created,
                           attending_events=events_attending)

event_finder/templates/base.html
<!doctype html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <!-- Meta SEO Tags -->
    <meta name="author" content="Ethan Pitt">
    <meta name="description" content="Event Haven - Find Events near you!">
    <meta name="keywords" content="Events, Event, community,">
    <!-- Bootstrap CSS Link-->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
    <!-- Font Awesome Link-->
    <script src="https://kit.fontawesome.com/42859c0fc4.js" crossorigin="anonymous"></script>
    <!-- Custom CSS Link-->
    <link rel="stylesheet" href="{{ url_for('static', filename='css/styles.css') }}">
    <!-- Favicon Link -->
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='imgs/favicon.ico') }}">

    <title>{% block title %} Event Haven {% endblock %}</title>
</head>
<body>
<!-- Navbar   -->
<nav class="navbar navbar-light navbar-expand-md py-4 text-uppercase">
    <div class="container-fluid">
        <a href="{{ url_for('event.index') }}" class="navbar-brand">Event Haven</a>
        <button class="navbar-toggler" data-bs-toggle="collapse" data-bs-target="#navbarNav"
                aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle Navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="navbar-collapse collapse justify-content-end" id="navbarNav">
            <ul class="navbar-nav justify-content-end align-items-end">
                <li class="nav-item">
                    <a href="{{ url_for('event.events') }}" class="nav-link">Events</a>
                </li>
                {% if session.user_uuid %}
                    <li class="nav-item">
                        <a href="{{ url_for('event.profile', uuid=session['user_uuid']) }}"
                           class="nav-link">Profile</a>
                    </li>
                    {% if session.admin == True %}
                        <li class="nav-item">
                            <a href="{{ url_for('admin.admin_page') }}" class="nav-link">Administration</a>
                        </li>
                    {% endif %}
                    <li class="nav-item">
                        <a class="btn" role="button" href="{{ url_for('auth.logout') }}">Logout</a>
                    </li>
                {% else %}
                    {# If user is not logged in, display Register/Login #}
                    <li class="nav-item">
                        <a class="btn" role="button" href="{{ url_for('auth.register') }}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="btn" role="button" href="{{ url_for('auth.login') }}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

<!-- Flash Section   -->
{% with flashed_messages = get_flashed_messages() %}
    {% if flashed_messages %}
        <section class="mt-4 mb-4">
            {% for message in flashed_messages %}
                <div class="container text-center">
                    <div class="row">
                        <div class="center-align text-muted">
                            {{ message }}
                        </div>
                    </div>
                </div>
            {% endfor %}
        </section>
    {% endif %}
{% endwith %}

<!-- Content Container -->
<div class="page-container">
    <div class="content-wrap">
        <div class="container-fluid content-container">
            {% block content %}

            {% endblock %}
        </div>
    </div>
</div>
<!-- Footer -->
<footer class="text-center footer">
    <div class="container py-3 py-lg-5">
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="{{ url_for('event.index') }}" class="link">Home</a>
            </li>
            <li class="list-inline-item">
                <a href="{{ url_for('event.events') }}" class="link">Events</a>
            </li>
        </ul>
        <ul class="list-inline">
            <li class="list-inline-item">
                <a href="https://facebook.com" aria-label="FaceBook" target="_blank">
                    <i class="fa-brands fa-facebook"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="https://instagram.com" aria-label="Instagram" target="_blank">
                    <i class="fa-brands fa-instagram"></i>
                </a>
            </li>
            <li class="list-inline-item">
                <a href="https://github.com/InfiniteEndeavours/" aria-label="GitHub" target="_blank">
                    <i class="fa-brands fa-github"></i>
                </a>
            </li>
        </ul>
        <p class="text-muted mb-1">
            Copyright © 2023 Event Haven
        </p>
    </div>
</footer>

<!-- jQuery and Boostrap JS links -->
<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.6.4/jquery.min.js"
        integrity="sha512-pumBsjNRGGqkPzKHndZMaAG+bir374sORyzM3uulLV14lN5LyykqNk8eEeUlUkB3U0M4FApyaHraT65ihJhDpQ=="
        crossorigin="anonymous" referrerpolicy="no-referrer"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-kenU1KFdBIe4zVF0s0G1M5b4hcpxyD9F7jL+jjXkk+Q2h455rYXK/7HAuoJl+0I4"
        crossorigin="anonymous"></script>
</body>
</html>

event_finder/templates/index.html
{% extends "base.html" %}

{% if 'user_uuid' in session %}
    {% set uuid = session['user_uuid'] %}
{% else %}
    {% set uuid = "not_set" %}
{% endif %}

{% block content %}
    <section>
        <div id="image-div">
            <div class="container h-100">
                <div class="row h-100">
                    <div class="col-md-6 text-center d-flex d-sm-flex d-md-flex justify-content-end align-items-center justify-content-md-end justify-content-lg-end ms-auto">
                        <div id="image-text">
                            <h1>Event Haven, <br> The Home Of Events</h1>
                            <p class="my-3">The last site you'll need to find events near you!</p>
                            <a class="btn btn-lg me-2 my-1" role="button" href="{{ url_for('event.events') }}">Events
                                <i class="fa-solid fa-calendar-days"></i></a>
                            <a class="btn btn-lg my-1" role="button" href="{{ url_for('event.profile', uuid=uuid) }}">Profile
                                <i class="fa-solid fa-user"></i></a>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    {% if event_one and event_two %}
        <section>
            <div id="card-section" class="container">
                <h1 class="text-center">Featured Events</h1>
                <div class="row">
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body text-center">
                                <h2 class="card-title h4">{{ event_one.title }}</h2>
                                <p class="card-text">{{ event_one.description }}</p>
                                <a href="{{ url_for('event.event_info', event_id=event_one.id) }}"
                                   class="btn">Event Information</a>
                            </div>
                        </div>
                    </div>
                    <div class="col-md-6">
                        <div class="card">
                            <div class="card-body text-center">
                                <h2 class="card-title h4">{{ event_two.title }}</h2>
                                <p class="card-text">{{ event_two.description }}</p>
                                <a href="{{ url_for('event.event_info', event_id=event_two.id) }}"
                                   class="btn">Event Information</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </section>
    {% endif %}
{% endblock %}

event_finder/templates/profile.html
{% extends "base.html" %}

{% block title %}Event Haven - Profile{% endblock %}

{% block content %}
    <div class="row">
        <div class="col-xs-12 col-md-4">
            <div class="card">
                <div class="card-body text-center">
                    <i class="fas fa-user-circle fa-6x mb-3"></i>
                    <p class="card-title h5">Username: {{ user.username }}</p>
                    <p class="card-text">Name: {{ profile.first_name }} {{ profile.last_name }}</p>
                </div>
            </div>
        </div>
        <div class="col-xs-12 col-md-4">
            <h2 class="text-center">Events Attending</h2>
            {% for event in attending_events %}
                <div class="card">
                    <div class="card-body text-center">
                        <p class="card-title h5">{{ event.title }}</p>
                        <div class="card-text">
                            <small>{{ event.date.strftime('%A, %b %d, %Y') }} - {{ event.start_time }}</small>
                            <br>
                            <small>{{ event.location }}</small>
                            <br>
                            <a href="{{ url_for('event.event_info', event_id=event.id) }}" class="btn">View Event</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
        <div class="col-xs-12 col-md-4">
            <h2 class="text-center">Events Created</h2>
            {% for event in created_events %}
                <div class="card">
                    <div class="card-body text-center">
                        <p class="card-title h5">{{ event.title }}</p>
                        <div class="card-text">
                            <small>{{ event.date.strftime('%A, %b %d, %Y') }} - {{ event.start_time }}</small>
                            <br>
                            <small>{{ event.location }}</small>
                            <br>
                            <a href="{{ url_for('event.event_info', event_id=event.id) }}" class="btn">View Event</a>
                        </div>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>
{% endblock %}